import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import type { BottomTabNavigationProp } from '@react-navigation/bottom-tabs';
import { colors } from '../constants/colors';
import { usePrediction } from '../context/PredictionContext';
import { t } from '../i18n/translations';
import type { BottomTabParamList } from '../navigation/AppNavigator';

export default function HomeScreen() {
  const navigation = useNavigation<BottomTabNavigationProp<BottomTabParamList>>();
  const { language, setLanguage, resetDraft } = usePrediction();
  const text = (key: Parameters<typeof t>[1]) => t(language, key);
  const start = () => { resetDraft(); navigation.navigate('Prediction', { screen: 'Location' }); };
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View style={styles.brand}><View style={styles.logo}><Ionicons name="leaf" size={25} color={colors.white} /></View><View><Text style={styles.appName}>{text('appName')}</Text><Text style={styles.tagline}>{text('tagline')}</Text></View></View><View style={styles.lang}>{(['rw', 'en'] as const).map((item) => <Pressable key={item} onPress={() => setLanguage(item)} style={[styles.langButton, language === item && styles.langActive]}><Text style={[styles.langText, language === item && styles.langActiveText]}>{item.toUpperCase()}</Text></Pressable>)}</View></View>
    <Text style={styles.greeting}>{text('homeGreeting')}</Text><Text style={styles.title}>{text('homeTitle')}</Text><Text style={styles.description}>{text('homeDescription')}</Text>
    <View style={styles.card}><View style={styles.iconBox}><Ionicons name="analytics-outline" size={30} color={colors.darkGreen} /></View><Text style={styles.cardTitle}>{text('startYourPrediction')}</Text><Text style={styles.cardDescription}>{text('homeDescription')}</Text><Pressable onPress={start} style={styles.primary}><Text style={styles.primaryText}>{text('start')}</Text><Ionicons name="arrow-forward" size={20} color={colors.white} /></Pressable></View>
    <View style={styles.rowBetween}><Text style={styles.sectionTitle}>{text('how')}</Text></View>
    <View style={styles.steps}>{[text('chooseLocation'), text('enterDetails'), text('getEstimate')].map((item, index) => <View key={item} style={styles.step}><View style={styles.number}><Text style={styles.numberText}>{index + 1}</Text></View><Text style={styles.stepText}>{item}</Text></View>)}</View>
    <View style={styles.notice}><Ionicons name="information-circle-outline" size={21} color={colors.warningText} /><Text style={styles.noticeText}>{text('estimateOnly')}</Text></View><View style={styles.lightRow}><Ionicons name="phone-portrait-outline" size={18} color={colors.primary} /><Text style={styles.lightText}>{text('lowData')}</Text></View>
  </ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe:{flex:1,backgroundColor:colors.background},content:{padding:20,paddingBottom:40},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:30},brand:{flexDirection:'row',alignItems:'center',flex:1},logo:{width:44,height:44,borderRadius:14,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center',marginRight:10},appName:{fontSize:17,fontWeight:'800',color:colors.text},tagline:{fontSize:11,color:colors.secondaryText,marginTop:2},lang:{flexDirection:'row',backgroundColor:colors.lightGreen,padding:3,borderRadius:10},langButton:{paddingVertical:7,paddingHorizontal:8,borderRadius:8},langActive:{backgroundColor:colors.primary},langText:{fontSize:12,fontWeight:'800',color:colors.primary},langActiveText:{color:colors.white},greeting:{fontSize:16,fontWeight:'700',color:colors.primary,marginBottom:8},title:{fontSize:29,lineHeight:37,fontWeight:'800',color:colors.text,marginBottom:12},description:{fontSize:15,lineHeight:23,color:colors.secondaryText,marginBottom:22},card:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:20,padding:20,marginBottom:26},iconBox:{width:56,height:56,borderRadius:18,backgroundColor:colors.lightGreen,alignItems:'center',justifyContent:'center',marginBottom:15},cardTitle:{fontSize:21,fontWeight:'800',color:colors.text,marginBottom:7},cardDescription:{fontSize:14,lineHeight:21,color:colors.secondaryText,marginBottom:18},primary:{minHeight:54,borderRadius:14,backgroundColor:colors.primary,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9},primaryText:{color:colors.white,fontSize:15,fontWeight:'800'},rowBetween:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:12},sectionTitle:{fontSize:20,fontWeight:'800',color:colors.text},savedLink:{color:colors.primary,fontWeight:'700'},steps:{backgroundColor:colors.white,borderRadius:18,borderWidth:1,borderColor:colors.border,padding:17,marginBottom:20},step:{flexDirection:'row',alignItems:'center',marginVertical:8},number:{width:32,height:32,borderRadius:16,backgroundColor:colors.lightGreen,alignItems:'center',justifyContent:'center',marginRight:12},numberText:{fontWeight:'800',color:colors.primary},stepText:{fontSize:14,fontWeight:'600',color:colors.text,flex:1},notice:{flexDirection:'row',gap:9,backgroundColor:colors.warning,borderRadius:14,padding:14,marginBottom:18},noticeText:{flex:1,fontSize:13,lineHeight:19,color:colors.warningText},lightRow:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},lightText:{fontSize:13,color:colors.secondaryText} });