import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { colors } from '../constants/colors';
import { usePrediction } from '../context/PredictionContext';
import { t } from '../i18n/translations';
import type { LandUnit, Season } from '../types';
import type { PredictionStackParamList } from '../navigation/AppNavigator';
import { seasonLabels } from '../data/seasons';

export default function LandSeasonScreen() {
  const nav = useNavigation<NativeStackNavigationProp<PredictionStackParamList>>();
  const { language, draft, updateDraft } = usePrediction();
  const text = (key: Parameters<typeof t>[1]) => t(language, key);
  const [size, setSize] = useState(draft.landSize ? String(draft.landSize) : '');
  const [unit, setUnit] = useState<LandUnit>(draft.unit || 'hectares');
  const [season, setSeason] = useState<Season | undefined>(draft.season);
  const [agriculturalYear, setAgriculturalYear] = useState(draft.agriculturalYear || new Date().getFullYear());
  const [error, setError] = useState('');
  const seasonDescription = (item: Season) => { const [start, end] = seasonLabels[item].split(' – '); return `${text(start.toLowerCase() as Parameters<typeof t>[1])} – ${text(end.toLowerCase() as Parameters<typeof t>[1])}`; };
  const selectSeason = (item: Season) => { setSeason(item); setError(''); updateDraft({ season: item, agriculturalYear, plantingMonth: undefined, plantingCalendarYear: undefined, plantingDateLabel: undefined }); };
  const next = () => { const value = Number(size); if (!size.trim() || !Number.isFinite(value) || value <= 0) { setError(text('positiveLand')); return; } if (!season) { setError(text('seasonRequired')); return; } if (!agriculturalYear) { setError(text('agriculturalYearRequired')); return; } updateDraft({ landSize:value, unit, landHectares:unit === 'hectares' ? value : value / 10000, season, agriculturalYear }); nav.navigate('FarmingInfo'); };
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.step}>3 / 4</Text><Text style={s.title}>{text('landSeason')}</Text><Text style={s.desc}>{text('landDescription')}</Text><View style={s.card}><Text style={s.label}>{text('landSize')}</Text><TextInput value={size} onChangeText={setSize} keyboardType="decimal-pad" placeholder="1.5" placeholderTextColor={colors.secondaryText} style={s.input} accessibilityLabel={text('landSize')} /><Text style={s.label}>{text('unit')}</Text><View style={s.row}>{(['hectares','square metres'] as LandUnit[]).map((item) => <Pressable key={item} onPress={() => setUnit(item)} style={[s.choice, unit === item && s.choiceSelected]}><Text style={[s.choiceText, unit === item && s.choiceTextSelected]}>{item === 'hectares' ? text('hectares') : text('squareMetres')}</Text></Pressable>)}</View><Text style={s.label}>{text('season')}</Text><View style={s.seasonGrid}>{(['A','B','C'] as Season[]).map((item) => <Pressable key={item} onPress={() => selectSeason(item)} style={[s.seasonCard, season === item && s.choiceSelected]}><Text style={[s.seasonTitle, season === item && s.choiceTextSelected]}>{text('seasonLabel')} {item}</Text><Text style={s.seasonMonths}>{seasonDescription(item)}</Text>{season === item && <Ionicons name="checkmark-circle" size={20} color={colors.primary} style={s.check} />}</Pressable>)}</View><Text style={s.label}>{text('agriculturalYear')}</Text><View style={s.yearRow}>{[agriculturalYear - 1, agriculturalYear, agriculturalYear + 1, agriculturalYear + 2].map((item) => <Pressable key={item} onPress={() => { setAgriculturalYear(item); updateDraft({ agriculturalYear: item, plantingMonth: undefined, plantingCalendarYear: undefined, plantingDateLabel: undefined }); }} style={[s.year, agriculturalYear === item && s.choiceSelected]}><Text style={[s.choiceText, agriculturalYear === item && s.choiceTextSelected]}>{item}</Text></Pressable>)}</View>{error ? <Text style={s.error}>{error}</Text> : null}</View><View style={s.actions}><Pressable style={s.back} onPress={() => nav.goBack()}><Text style={s.backText}>{text('back')}</Text></Pressable><Pressable style={s.primary} onPress={next}><Text style={s.primaryText}>{text('continue')}</Text><Ionicons name="arrow-forward" size={20} color={colors.white} /></Pressable></View></ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({ safe:{flex:1,backgroundColor:colors.background},content:{padding:20,paddingBottom:40},step:{fontWeight:'800',color:colors.primary,marginBottom:8},title:{fontSize:29,fontWeight:'800',color:colors.text},desc:{fontSize:15,lineHeight:22,color:colors.secondaryText,marginVertical:10},card:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:18,padding:17,marginTop:10},label:{fontSize:14,fontWeight:'800',color:colors.text,marginTop:14,marginBottom:7},input:{height:52,borderWidth:1,borderColor:colors.border,borderRadius:12,paddingHorizontal:14,color:colors.text,fontSize:16},row:{flexDirection:'row',gap:8,flexWrap:'wrap'},choice:{minHeight:48,borderRadius:12,borderWidth:1,borderColor:colors.border,justifyContent:'center',paddingHorizontal:13,flex:1},choiceSelected:{backgroundColor:colors.lightGreen,borderColor:colors.primary},choiceText:{color:colors.text,fontSize:13,textAlign:'center'},choiceTextSelected:{color:colors.darkGreen,fontWeight:'800'},seasonGrid:{gap:9},seasonCard:{minHeight:68,borderRadius:13,borderWidth:1,borderColor:colors.border,padding:12,position:'relative'},seasonTitle:{fontSize:15,fontWeight:'800',color:colors.text},seasonMonths:{fontSize:13,color:colors.secondaryText,marginTop:4},check:{position:'absolute',right:12,top:12},yearRow:{flexDirection:'row',gap:7},year:{minHeight:45,borderRadius:11,borderWidth:1,borderColor:colors.border,justifyContent:'center',alignItems:'center',paddingHorizontal:10,flex:1},error:{color:colors.error,fontSize:13,marginTop:14},actions:{flexDirection:'row',gap:10,marginTop:26},back:{minHeight:54,borderRadius:14,borderWidth:1,borderColor:colors.primary,justifyContent:'center',alignItems:'center',paddingHorizontal:20},backText:{color:colors.primary,fontWeight:'800'},primary:{flex:1,minHeight:54,borderRadius:14,backgroundColor:colors.primary,flexDirection:'row',gap:8,justifyContent:'center',alignItems:'center'},primaryText:{color:colors.white,fontWeight:'800'}});